project:
  type: website

book:
  title: "ON LiMiT Feasibility Study Data"
  # TODO: Set the URL of the website
  site-url: ""
  repo-url: "https://github.com/onlimit-study/feasibility-data"
  author:
    - name: "Kristiane Beicher"
      affiliation: "TODO: Fill in your affiliation"
      orcid: "TODO: Fill in your ORCID"
  # TODO: Set favicon if relevant.
  # favicon: ""
  repo-branch: main
  repo-actions: [issue, edit, source]
  search:
    location: navbar
    type: textbox
  chapters:
    - index.qmd
  #  - part: "Sections"
  #    chapters:
  #    - path/to/file.qmd
  # appendices:
  #  - path/to/file.qmd
  tools:
    - icon: github
      href: "https://github.com/onlimit-study/feasibility-data"
      aria-label: "GitHub icon: Source repository"
  page-footer:
    center:
      - text: "Code under MIT License"
        href: "LICENSE-MIT.md"


format:
  html:
    theme:
      - litera
      - custom-styles.scss
