import seedcase_sprout as sp

# from .resource_properties import resource_properties

package_properties = sp.PackageProperties(
    ## Required:
    name="feasibility-data",
    title="ON LiMiT Feasibility Study Data",
    description="Full data set on 24 participants in the feasibility arm of the "
    "ON LiMiT study. ON LiMiT is looking at remission of type 2 diabetes using "
    "diet and exercise.",
    licenses=[
        sp.LicenseProperties(
            ## Required:
            name="CC0-1.0",
            ## Optional:
            path="https://creativecommons.org/publicdomain/zero/1.0/",
            title="CC0 1.0 Universal",
        ),
    ],
    ## Optional:
    homepage="https://onlimit.org",
    # contributors=[
    #    sp.ContributorProperties(
    #        ## Required:
    #        title="",
    #        ## Optional:
    #        path="",
    #        email="kris.beicher@clin.au.dk",
    #        given_name="Kristiane",
    #        family_name="Beicher",
    #        organization="Steno Diabetes Centre Aarhus",
    #        roles=["Creator", "DataManager", "DataCurator", "ContactPerson"],
    #    ),
    # ],
    # keywords=[""],
    # image="",
    # sources=[
    #    sp.SourceProperties(
    #        ## Required:
    #        title="",
    #        ## Optional:
    #        path="",
    #        email="",
    #        version="",
    #    ),
    # ],
    # resources=[
    #     resource_properties,
    # ],
    ## Autogenerated:
    id="63e1c02c-bbe6-455c-a0b7-3bc5f453f3af",
    version="0.2.0",
    created="2025-12-09T15:00:26+01:00",
)
