import seedcase_sprout as sp

# from .resource_properties import resource_properties

package_properties = sp.PackageProperties(
    ## Required:
    name="feasibility-data",
    title="",
    description="",
    licenses=[
        sp.LicenseProperties(
            ## Required:
            name="",
            ## Optional:
            # path="",
            # title="",
        ),
    ],
    ## Optional:
    # homepage="",
    # contributors=[
    #    sp.ContributorProperties(
    #        ## Required:
    #        title="",
    #        ## Optional:
    #        path="",
    #        email="",
    #        given_name="",
    #        family_name="",
    #        organization="",
    #        roles=[""],
    #    ),
    # ],
    # keywords=[""],
    # image="",
    # sources=[
    #    sp.SourceProperties(
    #        ## Required:
    #        title="",
    #        ## Optional:
    #        path="",
    #        email="",
    #        version="",
    #    ),
    # ],
    # resources=[
    #     resource_properties,
    # ],
    ## Autogenerated:
    id="63e1c02c-bbe6-455c-a0b7-3bc5f453f3af",
    version="0.2.0",
    created="2025-12-09T15:00:26+01:00",
)
